name: Deploy to AWS Elastic Beanstalk
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build and Publish"]
    types:
      - completed

env:
  AWS_REGION: us-east-1
  EB_APPLICATION_NAME: weshop-2024
  EB_ENVIRONMENT_NAME: weshop-2024-sboot-j5-t3
  DEPLOY_PACKAGE_NAME: weshop-app-${{ github.sha }}.jar

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_EBS_AWS_2024 }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EBS_AWS_2024 }}
          aws-region: ${{ env.AWS_REGION }}
          
      - name: Download artifact from GitHub Packages
        run: |
          # Add GitHub token to access packages
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
          
          # Download the JAR file using curl
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -L https://maven.pkg.github.com/pingv/weshop-2024/com/pingv/weshop/latest/weshop-latest.jar \
               -o ${{ env.DEPLOY_PACKAGE_NAME }}

      - name: Check if Environment Exists
        id: env_check
        run: |
          aws elasticbeanstalk describe-environments \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --environment-names ${{ env.EB_ENVIRONMENT_NAME }} \
            --query "Environments[?Status=='Ready']" \
            --output text || echo "NOT_FOUND"

      - name: Create Environment if Not Exists
        if: steps.env_check.outputs.result == 'NOT_FOUND'
        run: |
          echo "Environment does not exist. Creating it now..."
          aws elasticbeanstalk create-environment \
            --application-name ${{ env.EB_APPLICATION_NAME }} \
            --environment-name ${{ env.EB_ENVIRONMENT_NAME }} \
            --solution-stack-name "64bit Amazon Linux 2 v3.4.4 running Corretto 11" \
            --option-settings file://option-settings.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID_EBS_AWS_2024 }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EBS_AWS_2024 }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: ${{ github.sha }}
          region: ${{ env.AWS_REGION }}
          deployment_package: ${{ env.DEPLOY_PACKAGE_NAME }}
          use_existing_version_if_available: false
          wait_for_deployment: true
          wait_for_environment_recovery: 300
