name: Deploy to EC2

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Store the SSH key
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          # Add host key checking exception
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          
          # Set the exact JAR filename
          JAR_FILE="target/weshop-2024-0.0.1-SNAPSHOT.jar"
          
          echo "Copying JAR file to EC2..."
          # First, copy to home directory (which we have permission to write to)
          scp -i ~/.ssh/deploy_key $JAR_FILE $EC2_USERNAME@$EC2_HOST:~/app.jar
          
          echo "Moving JAR to /opt/myapp and setting permissions..."
          # Then use SSH to execute sudo commands to move the file and set permissions
          ssh -i ~/.ssh/deploy_key $EC2_USERNAME@$EC2_HOST '
            sudo mv ~/app.jar /opt/myapp/app.jar
            sudo chown root:root /opt/myapp/app.jar
            sudo chmod 644 /opt/myapp/app.jar
            sudo systemctl restart springapp
          '
          
          # Clean up sensitive files
          rm -f ~/.ssh/deploy_key
          rm -f ~/.ssh/config